use  wallethub;

CREATE TABLE `access_log` (
  `ACCESS_DATE` DATETIME DEFAULT NULL,
  `IP` VARCHAR(50) DEFAULT NULL,
  `REQUEST` VARCHAR(2000) DEFAULT NULL,
  `STATUS` VARCHAR(50) DEFAULT NULL,
  `USER_AGENT` VARCHAR(2000) DEFAULT NULL
);

CREATE TABLE `blocked_ip` (
  `IP` VARCHAR(50) NOT NULL,
  `REASON` VARCHAR(2000) NULL
);
